### PR TITLE
update test cards

### PR DESCRIPTION
**Pull request by zach-hammond**
Updating the test cards that have changed, per https://developers.bluesnap.com/reference/test-credit-cards

### CODE REVIEW

**Review by Quickgs — APPROVED** [review]
Is there someway we can put up a reminder or something for the NEXT group down the road, so they dont run into the same thing 3 years from now?

(Including possibly us?)

**Comment by zach-hammond** [comment]
> Is there someway we can put up a reminder or something for the NEXT group down the road, so they dont run into the same thing 3 years from now?

@Quickgs we could just do a slack reminder but who knows what channels will be around in three years. the pain was relatively low (failed tests) and the fix was equally as low effort, so the best thing is prob just docs indicating that this thing even exists for whatever poor soul ends up supporting it in 3 years

image

**Review by jasonvideoblocks — APPROVED** [review]
I genuinely forgot about this repo

**Review by oljasshaiken — APPROVED** [review]
🚀

**Pull request merged**
